spring.application.name=aio-fitness
spring.datasource.url=PLACEHOLDER
spring.datasource.username=PLACEHOLDER
spring.datasource.password=PLACEHOLDER
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect